/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.4.0 Fri Apr 28 18:22:09 2023.
 */

#ifndef IM1_A_EVB_V1_0_0_211018_H
#define IM1_A_EVB_V1_0_0_211018_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define IM1_A_EVB_V1_0_0_211018_IMU_ACCEL_RAW_FRAME_ID (0x401u)
#define IM1_A_EVB_V1_0_0_211018_IMU_ANG_RATE_RAW_FRAME_ID (0x402u)

/* Frame lengths in bytes. */
#define IM1_A_EVB_V1_0_0_211018_IMU_ACCEL_RAW_LENGTH (8u)
#define IM1_A_EVB_V1_0_0_211018_IMU_ANG_RATE_RAW_LENGTH (8u)

/* Extended or standard frame types. */
#define IM1_A_EVB_V1_0_0_211018_IMU_ACCEL_RAW_IS_EXTENDED (0)
#define IM1_A_EVB_V1_0_0_211018_IMU_ANG_RATE_RAW_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/**
 * Signals in message IMU_AccelRaw.
 *
 * All signal values are as on the CAN bus.
 */
struct im1_a_evb_v1_0_0_211018_imu_accel_raw_t {
    /**
     * Range: -524288..524287 (-524.288..524.287 m/s/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t accel_raw_x;

    /**
     * Range: -524288..524287 (-524.288..524.287 m/s/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t accel_raw_y;

    /**
     * Range: -524288..524287 (-524.288..524.287 m/s/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t accel_raw_z;
};

/**
 * Signals in message IMU_AngRateRaw.
 *
 * All signal values are as on the CAN bus.
 */
struct im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_t {
    /**
     * Range: -524288..524287 (-524.288..524.287 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t ang_rate_raw_x;

    /**
     * Range: -524288..524287 (-524.288..524.287 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t ang_rate_raw_y;

    /**
     * Range: -524288..524287 (-524.288..524.287 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int32_t ang_rate_raw_z;
};

/**
 * Pack message IMU_AccelRaw.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int im1_a_evb_v1_0_0_211018_imu_accel_raw_pack(
    uint8_t *dst_p,
    const struct im1_a_evb_v1_0_0_211018_imu_accel_raw_t *src_p,
    size_t size);

/**
 * Unpack message IMU_AccelRaw.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int im1_a_evb_v1_0_0_211018_imu_accel_raw_unpack(
    struct im1_a_evb_v1_0_0_211018_imu_accel_raw_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_is_in_range(int32_t value);

/**
 * Pack message IMU_AngRateRaw.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_pack(
    uint8_t *dst_p,
    const struct im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_t *src_p,
    size_t size);

/**
 * Unpack message IMU_AngRateRaw.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_unpack(
    struct im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_is_in_range(int32_t value);


#ifdef __cplusplus
}
#endif

#endif
