/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.4.0 Fri Apr 28 18:22:09 2023.
 */

#include <string.h>

#include "im1_a_evb_v1_0_0_211018.h"

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int im1_a_evb_v1_0_0_211018_imu_accel_raw_pack(
    uint8_t *dst_p,
    const struct im1_a_evb_v1_0_0_211018_imu_accel_raw_t *src_p,
    size_t size)
{
    uint32_t accel_raw_x;
    uint32_t accel_raw_y;
    uint32_t accel_raw_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    accel_raw_x = (uint32_t)src_p->accel_raw_x;
    dst_p[0] |= pack_left_shift_u32(accel_raw_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(accel_raw_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(accel_raw_x, 16u, 0x0fu);
    accel_raw_y = (uint32_t)src_p->accel_raw_y;
    dst_p[2] |= pack_left_shift_u32(accel_raw_y, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(accel_raw_y, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(accel_raw_y, 12u, 0xffu);
    accel_raw_z = (uint32_t)src_p->accel_raw_z;
    dst_p[5] |= pack_left_shift_u32(accel_raw_z, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(accel_raw_z, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(accel_raw_z, 16u, 0x0fu);

    return (8);
}

int im1_a_evb_v1_0_0_211018_imu_accel_raw_unpack(
    struct im1_a_evb_v1_0_0_211018_imu_accel_raw_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t accel_raw_x;
    uint32_t accel_raw_y;
    uint32_t accel_raw_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_raw_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    accel_raw_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    accel_raw_x |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((accel_raw_x & (1u << 19)) != 0u) {
        accel_raw_x |= 0xfff00000u;
    }

    dst_p->accel_raw_x = (int32_t)accel_raw_x;
    accel_raw_y = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    accel_raw_y |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    accel_raw_y |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((accel_raw_y & (1u << 19)) != 0u) {
        accel_raw_y |= 0xfff00000u;
    }

    dst_p->accel_raw_y = (int32_t)accel_raw_y;
    accel_raw_z = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    accel_raw_z |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    accel_raw_z |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((accel_raw_z & (1u << 19)) != 0u) {
        accel_raw_z |= 0xfff00000u;
    }

    dst_p->accel_raw_z = (int32_t)accel_raw_z;

    return (0);
}

int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_x_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_y_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int32_t im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_accel_raw_accel_raw_z_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_pack(
    uint8_t *dst_p,
    const struct im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_t *src_p,
    size_t size)
{
    uint32_t ang_rate_raw_x;
    uint32_t ang_rate_raw_y;
    uint32_t ang_rate_raw_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ang_rate_raw_x = (uint32_t)src_p->ang_rate_raw_x;
    dst_p[0] |= pack_left_shift_u32(ang_rate_raw_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(ang_rate_raw_x, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(ang_rate_raw_x, 16u, 0x0fu);
    ang_rate_raw_y = (uint32_t)src_p->ang_rate_raw_y;
    dst_p[2] |= pack_left_shift_u32(ang_rate_raw_y, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u32(ang_rate_raw_y, 4u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(ang_rate_raw_y, 12u, 0xffu);
    ang_rate_raw_z = (uint32_t)src_p->ang_rate_raw_z;
    dst_p[5] |= pack_left_shift_u32(ang_rate_raw_z, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(ang_rate_raw_z, 8u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(ang_rate_raw_z, 16u, 0x0fu);

    return (8);
}

int im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_unpack(
    struct im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t ang_rate_raw_x;
    uint32_t ang_rate_raw_y;
    uint32_t ang_rate_raw_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    ang_rate_raw_x = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    ang_rate_raw_x |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    ang_rate_raw_x |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);

    if ((ang_rate_raw_x & (1u << 19)) != 0u) {
        ang_rate_raw_x |= 0xfff00000u;
    }

    dst_p->ang_rate_raw_x = (int32_t)ang_rate_raw_x;
    ang_rate_raw_y = unpack_right_shift_u32(src_p[2], 4u, 0xf0u);
    ang_rate_raw_y |= unpack_left_shift_u32(src_p[3], 4u, 0xffu);
    ang_rate_raw_y |= unpack_left_shift_u32(src_p[4], 12u, 0xffu);

    if ((ang_rate_raw_y & (1u << 19)) != 0u) {
        ang_rate_raw_y |= 0xfff00000u;
    }

    dst_p->ang_rate_raw_y = (int32_t)ang_rate_raw_y;
    ang_rate_raw_z = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    ang_rate_raw_z |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    ang_rate_raw_z |= unpack_left_shift_u32(src_p[7], 16u, 0x0fu);

    if ((ang_rate_raw_z & (1u << 19)) != 0u) {
        ang_rate_raw_z |= 0xfff00000u;
    }

    dst_p->ang_rate_raw_z = (int32_t)ang_rate_raw_z;

    return (0);
}

int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_x_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_y_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int32_t im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool im1_a_evb_v1_0_0_211018_imu_ang_rate_raw_ang_rate_raw_z_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}
